# ansible/secrets.yml
# Private vars — tokens, keys. Not committed to git.

admin_keys:
  - "ssh-ed25519 AAAAC... ..."
  - "ssh-ed25519 AAAAC... ..."
  - "ssh-ed25519 AAAAC... ..."
ansible_key: "ssh-ed25519 AAAAC... ..."
pve_api_user: "ansible@pve"
pve_api_token_id: "ansible"
pve_api_token_secret: "..."
